// Short (~500 word) accounting & finance explainers. One rotates per day.
const FINANCE_ARTICLES = [
  {
    id: 'accounting-equation',
    title: 'The Accounting Equation',
    body: `Every financial statement in the world ultimately rests on one simple equation: Assets = Liabilities + Equity. Assets are everything a business owns or controls that has value — cash, inventory, equipment, buildings, accounts receivable. Liabilities are everything it owes to others — loans, unpaid bills, bonds. Equity is what's left over for the owners once the liabilities are subtracted from the assets, often called "net worth" or "book value."

This equation always balances, by definition. If a company buys a $10,000 machine with cash, assets don't actually change in total — cash goes down by $10,000 and equipment goes up by $10,000. If the company instead borrows $10,000 to buy that machine, assets go up by $10,000 (the machine) and liabilities go up by $10,000 (the loan). Equity is untouched either way. This is the logic behind double-entry bookkeeping: every transaction has at least two effects that keep the equation in balance.

Why does this matter to you, even if you never touch a ledger? Because the same logic applies to your personal finances. Your "assets" are your cash, investments, home, and car. Your "liabilities" are your mortgage, student loans, and credit card balances. Your "equity" — your personal net worth — is the difference. Tracking net worth over time, rather than just your bank balance, is one of the simplest and most powerful habits in personal finance, because it captures the whole picture: it goes up when you save, pay down debt, or your investments grow, and it goes down when you take on debt or your assets lose value.

The accounting equation also explains why a business (or a person) can look "rich" on assets but still be in trouble. A company with $10 million in assets but $9.5 million in liabilities has only $500,000 in equity — a thin cushion. If asset values drop even slightly, equity can evaporate or turn negative, a situation called being "underwater" or "insolvent" on a book basis. This is exactly what happened to many banks and homeowners during the 2008 financial crisis: the assets (mortgages, homes) lost value, the liabilities (deposits, mortgage balances) stayed fixed, and equity collapsed or went negative.

One subtlety worth knowing: equity isn't just "money the owners put in." It's a running total of contributions (like stock issued to shareholders), plus accumulated profits that haven't been paid out (called "retained earnings"), minus any losses or dividends. That's why a profitable company that reinvests everything will show steadily growing equity even if the owners never add another dollar.

Next time you look at any balance sheet — a company's, or your own household's — try organizing it into these three buckets. Assets on one side, liabilities on the other, and equity as the difference. It's the same three-part structure whether you're looking at Apple's 10-K or your own bank and loan statements, and once it clicks, every other financial statement becomes much easier to read, because the income statement and cash flow statement are really just explanations of *how* and *why* equity and cash changed from one balance sheet to the next.`
  },
  {
    id: 'balance-sheet',
    title: 'How to Read a Balance Sheet',
    body: `A balance sheet is a snapshot — it shows what a company owns and owes at a single point in time, like a photo rather than a video. It's organized into the three buckets from the accounting equation: assets, liabilities, and equity, and (as the name promises) the two sides always balance.

Assets are typically listed in order of liquidity — how quickly they can be turned into cash. "Current assets" include cash, short-term investments, accounts receivable (money customers owe the company), and inventory — things expected to convert to cash within a year. "Non-current" or "long-term" assets include property, plant and equipment (PP&E), buildings, machinery, and intangible assets like patents, trademarks, and goodwill (the premium paid when acquiring another company above its book value).

Liabilities follow the same logic. "Current liabilities" are obligations due within a year: accounts payable (bills the company owes suppliers), short-term debt, accrued wages, and taxes payable. "Long-term liabilities" include bonds, long-term loans, and pension obligations that stretch beyond a year.

Equity, sometimes called "shareholders' equity" or "stockholders' equity," includes common stock (the par value of shares issued), additional paid-in capital (the amount investors paid above par value), retained earnings (cumulative profits kept in the business), and sometimes "treasury stock" (a negative number representing shares the company bought back).

A few quick checks turn a balance sheet from a wall of numbers into a story. First, compare current assets to current liabilities — this is the "current ratio," and it tells you whether a company can cover its near-term bills with its near-term resources. A ratio comfortably above 1 generally suggests good short-term liquidity; well below 1 can be a red flag (though context matters — some business models, like grocery chains, run efficiently on thin current ratios because they turn inventory into cash very quickly).

Second, look at the proportion of debt to equity. A company financed mostly by debt is "leveraged" — it can amplify returns when things go well, but it also amplifies losses and interest obligations when things go poorly. There's no single "right" ratio; capital-intensive industries like utilities or real estate typically carry more debt than software companies, which need little physical capital.

Third, watch how things change over time. A single balance sheet is a snapshot, but comparing this year's to last year's reveals trends: Is debt growing faster than assets? Is cash piling up or draining away? Is inventory growing faster than sales (a possible sign that products aren't selling)?

Finally, remember that a balance sheet reflects accounting values, not necessarily market values. A factory bought 30 years ago might be listed at its original cost minus depreciation, which could be far below what it's actually worth today — or, in the case of outdated equipment, far above. Reading a balance sheet well means treating it as a structured starting point for questions, not a final verdict on what a company — or a household — is "worth."`
  },
  {
    id: 'income-statement',
    title: 'How to Read an Income Statement',
    body: `While the balance sheet is a snapshot, the income statement (also called the profit & loss statement, or "P&L") is a video — it covers a period of time, like a quarter or a year, and shows how much money came in, how much went out, and what was left over.

It starts at the top with revenue (also called sales or "top line") — the total amount earned from selling goods or services, before any costs are subtracted. From there, the statement works downward through layers of expenses, each subtraction producing a meaningful subtotal.

First comes the cost of goods sold (COGS) — the direct costs of producing what was sold: materials, factory labor, shipping. Revenue minus COGS equals gross profit, and gross profit divided by revenue gives the gross margin — a percentage that tells you how much of each sales dollar is left after covering the direct cost of making the product. A software company might have gross margins above 70-80% because the cost of "producing" another copy of its product is nearly zero, while a grocery store might run at 25% because physical goods are expensive to source.

Next come operating expenses — costs not directly tied to producing the product, but to running the business: salaries for administrative staff, marketing, rent, research and development. Gross profit minus operating expenses gives operating income (sometimes called EBIT, for "earnings before interest and taxes"). This number is useful because it reflects how profitable the core business is, independent of how it's financed or taxed.

From operating income, the statement subtracts interest expense (the cost of any debt) and adds or subtracts other items like investment gains, then subtracts income tax expense. What's left is net income — the famous "bottom line." Net income is what belongs to shareholders; it either gets paid out as dividends or stays in the business as retained earnings, which flows into the equity section of the balance sheet.

A useful habit when reading an income statement is to convert every line to a percentage of revenue — this is called a "common-size" income statement. It instantly shows you the shape of a business: how much is eaten by production costs, how much by overhead, how much by interest and taxes, and what fraction survives as profit. Comparing these percentages over several years reveals whether a company is becoming more efficient (margins expanding) or less (margins shrinking), often well before the headline profit number tells the story.

One important caveat: net income is not the same as cash. The income statement includes non-cash items like depreciation (spreading the cost of an asset over its useful life) and follows "accrual accounting," which records revenue when it's earned and expenses when they're incurred — not necessarily when cash actually changes hands. A company can be "profitable" on paper while running low on cash, which is exactly why the cash flow statement exists as a third, equally important piece of the puzzle.`
  },
  {
    id: 'cash-flow-vs-profit',
    title: 'Cash Flow vs. Profit: Why They Differ',
    body: `"Profitable but broke" sounds like a contradiction, but it's one of the most common ways businesses fail — and it happens because profit and cash are measured differently. Understanding the gap between them is one of the most valuable things you can learn in finance, whether you run a business or just manage a household budget.

Profit (net income) is calculated using accrual accounting: revenue is recorded when it's earned, and expenses are recorded when they're incurred — regardless of when cash actually moves. If a consulting firm finishes a project in December and bills the client $50,000, it records $50,000 of revenue in December, even if the client doesn't pay until February. Meanwhile, cash flow only counts money that has actually arrived in or left a bank account.

This creates several common gaps. The first is accounts receivable: sales recorded as revenue but not yet collected in cash. A fast-growing company can show strong profits on paper while its cash balance shrinks, because it's extending more and more credit to customers faster than it's collecting on old invoices. The second is inventory: when a company buys raw materials or stock, cash goes out the door immediately, but the expense isn't recognized on the income statement until the goods are actually sold. A retailer stocking up for the holiday season will see cash drop well before the corresponding sales (and profit) show up.

The third major gap is capital expenditures versus depreciation. When a company buys a $1 million machine, the entire $1 million leaves the bank account at once — but the income statement only records a fraction of that cost each year as "depreciation" over the machine's useful life (say, $100,000 per year for 10 years). So in the year of purchase, cash flow drops by $1 million while profit drops by only $100,000; in the following nine years, profit reflects an expense ($100,000/year) that costs no actual cash at all.

The fourth gap is debt: loan principal repayments reduce cash but don't appear on the income statement at all (only the interest portion does), while taking out a new loan brings in cash without being counted as revenue.

This is why the cash flow statement exists as its own document, broken into three sections: cash from operating activities (the cash version of the income statement, adjusting for receivables, inventory, and non-cash items like depreciation), cash from investing activities (buying or selling long-term assets like equipment or investments), and cash from financing activities (borrowing, repaying debt, issuing stock, paying dividends).

The practical lesson translates directly to personal finance: your take-home pay minus your spending is your real "cash flow," but it can diverge sharply from your "net worth change" in any given month. You might have a great month on paper because your investments went up in value, while your checking account is nearly empty because of a big one-time expense. Tracking both — what you own (net worth) and what's actually moving through your accounts (cash flow) — gives a far more complete picture than either one alone, and it's exactly the discipline that keeps profitable businesses from accidentally running out of cash.`
  },
  {
    id: 'debits-and-credits',
    title: 'Debits and Credits: The Language of Bookkeeping',
    body: `"Debit" and "credit" are probably the most confusing words in accounting, mostly because their everyday meanings (a "credit" is good, a "debit" is bad — think of a credit card vs. a debit card) don't map cleanly onto their accounting meanings. In bookkeeping, debit simply means "left side of the ledger" and credit means "right side" — and whether that's "good" or "bad" depends entirely on what kind of account you're looking at.

The system is called double-entry bookkeeping because every single transaction is recorded twice: once as a debit in one account, and once as a credit in another account, for the same amount. This is the practical machinery behind the accounting equation (Assets = Liabilities + Equity) always balancing — every transaction shifts the books in a way that keeps both sides equal.

Here's the key rule to memorize: for asset and expense accounts, debits increase the balance and credits decrease it. For liability, equity, and revenue accounts, it's the opposite — credits increase the balance and debits decrease it. So when a business receives $1,000 cash from a customer for services rendered, it records a debit to Cash (an asset, increasing) and a credit to Revenue (which increases equity). Cash goes up, and so does the company's "claim" on that cash by its owners — both sides of the entry make sense once you see them as two views of the same event.

A practical example: imagine a small bakery buys $200 of flour on credit (meaning it will pay the supplier later). The bakery debits an expense or inventory account for $200 (an asset/expense increasing) and credits Accounts Payable for $200 (a liability increasing — the bakery now owes someone money). Later, when the bakery pays that bill, it debits Accounts Payable for $200 (the liability decreases) and credits Cash for $200 (the asset decreases). Notice that in both entries, the debits equal the credits — that's the check that keeps the books balanced.

Why does any of this matter if you're not a bookkeeper? Two reasons. First, it explains why financial software and bank statements sometimes seem to use "debit" and "credit" backwards from what you'd expect. When your bank sends you a statement, a "credit" to your account is good news for you (your balance went up) — but from the bank's perspective, your deposit account is a liability (money it owes you), and increasing a liability is a credit. Same word, opposite-feeling outcome, because you and the bank are looking at the same transaction from opposite sides of the ledger.

Second, understanding debits and credits is the foundation for reading any general ledger, QuickBooks report, or accounting export — which becomes valuable the moment you run a small business, manage a budget for a club or nonprofit, or just want to understand exactly how your accountant categorized something on your tax return. The terminology can feel arbitrary at first, but it's really just a 500-year-old convention (it dates back to 15th-century Italian merchants) for making sure two people's books always tell the same, balanced story.`
  },
  {
    id: 'time-value-of-money',
    title: 'The Time Value of Money',
    body: `If someone offered you $1,000 today or $1,000 in five years, you'd take it today — and not just because of impatience. A dollar today is worth more than a dollar in the future, and the precise reason why is the single most important idea in finance: the time value of money.

There are three reasons a dollar today beats a dollar later. First, you can invest it — put it in a savings account, bonds, or the stock market — and it can grow. Second, inflation tends to erode purchasing power over time, so a dollar in the future will likely buy less than a dollar today. Third, there's risk and uncertainty — a promise of future money might not be paid at all, while money in hand is money in hand.

Finance turns this idea into math through two related concepts: future value and present value. Future value answers, "If I invest $X today at a certain rate of return, what will it be worth later?" Present value flips the question around: "How much would I need today to end up with $Y in the future, given a certain rate of return?" The rate used in these calculations is often called the "discount rate," and it reflects both the return you could get elsewhere and the risk involved.

This is why interest rates affect almost everything in the economy. When interest rates rise, the discount rate used to value future cash flows rises too, which makes those future cash flows worth less in today's terms. This is a major reason stock prices often fall when central banks raise interest rates: a company's stock price is, in theory, the present value of all the cash it will ever generate, and if the discount rate goes up, that present value goes down — even if nothing about the company's actual future business has changed.

The time value of money also explains why "the rule of 72" is such a handy mental shortcut: divide 72 by an annual interest rate (as a percentage) to estimate how many years it takes for money to double. At 6% annual growth, money doubles in about 12 years (72 ÷ 6); at 9%, about 8 years. This single rule connects directly to retirement planning — it's why financial advisors emphasize starting to invest early. Money invested in your 20s has decades to compound, while the same amount invested in your 40s has far less time to double and double again.

On the borrowing side, the time value of money is exactly why loans charge interest — a lender is giving up the use of their money now in exchange for a promise of more money later, and that promise needs to be worth at least as much as having the cash today, adjusted for risk that the borrower might not repay. It's also why "buy now, pay later" and 0% financing offers can be deceptively appealing: if you can pay later for the same price you'd pay now, and you could have invested that money in the meantime, you've effectively been handed a small amount of free value — but only if you have the discipline to actually invest the difference rather than just spend it.`
  },
  {
    id: 'compound-interest',
    title: 'Compound Interest Explained',
    body: `Compound interest is often called the "eighth wonder of the world," and while that's a bit of marketing hyperbole, the underlying math really is powerful enough to deserve the reputation. The core idea is simple: interest earns interest. Once you understand how quickly that compounds, a lot of personal finance advice — start saving early, avoid high-interest debt, reinvest your dividends — stops sounding like generic wisdom and starts looking like simple arithmetic.

With simple interest, you earn a fixed return on your original amount (the "principal") every period, and that's it. If you invest $1,000 at 5% simple interest, you earn $50 every year, forever — $50 in year one, $50 in year two, and so on, totaling $1,500 after 10 years.

With compound interest, each period's interest gets added to the principal, and the next period's interest is calculated on that new, larger total. That same $1,000 at 5% compounded annually earns $50 in year one, bringing the balance to $1,050. In year two, 5% is calculated on $1,050, earning $52.50, bringing the balance to $1,102.50. It looks like a tiny difference at first — but the gap grows every year, because the base on which interest is calculated keeps getting bigger. After 10 years, the compounded amount is about $1,629 versus $1,500 for simple interest. After 30 years, it's about $4,322 versus $2,500 — nearly double.

The two variables that matter most for compounding are time and rate, and time is by far the more powerful of the two for most people, because it works exponentially while contributions only work additively. Consider two savers: one invests $5,000 per year from age 25 to 35 (10 years, then stops contributing but leaves the money invested) and another invests $5,000 per year from age 35 to 65 (30 years, three times as long). At a 7% annual return, the first saver — who contributed only $50,000 total — often ends up with more money at age 65 than the second saver, who contributed $150,000. The first saver's money simply had more decades to compound.

Compound interest cuts both ways, though — it's just as powerful (and just as dangerous) when it works against you. Credit card debt at 20%+ APR compounds the same way savings do, just in reverse: unpaid interest gets added to the balance, and next month's interest is charged on that larger balance. This is why credit card debt can spiral so quickly, and why paying more than the minimum payment — especially early — has an outsized effect on how quickly the balance shrinks.

The practical takeaway is that the single biggest lever most people have isn't finding an exotic high-return investment — it's time. A modest, steady rate of return (like a diversified index fund averaging historical market returns) given several extra decades will usually outperform a higher rate of return given only a few years. That's the entire argument, in miniature, for starting retirement contributions as early as possible, even if the amounts feel small at first.`
  },
  {
    id: 'ebitda',
    title: 'What Is EBITDA, and Why Does It Matter?',
    body: `EBITDA stands for "Earnings Before Interest, Taxes, Depreciation, and Amortization." It's one of the most commonly cited numbers in business news and investment analysis, and the name itself is basically a recipe: start with net income (the bottom-line "earnings"), and add back interest, taxes, depreciation, and amortization — four items that were subtracted to get to that bottom line in the first place.

Why would anyone want to "undo" those subtractions? Because each of the four items can vary for reasons that have nothing to do with how well the core business is actually performing, and EBITDA tries to strip those differences away to make companies more comparable.

Interest expense depends on how a company is financed — how much debt it carries and at what rate — not on how good its products are. Two companies could have identical operations, but if one is financed entirely with the owners' cash and the other is financed with a lot of borrowed money, the second will show lower net income purely because of interest payments. Taxes vary by jurisdiction, by available credits and deductions, and by quirks of tax law that change year to year — again, unrelated to operational performance. Depreciation and amortization are non-cash accounting allocations that spread the cost of past investments (in equipment, buildings, or acquired intangible assets) over many years; companies with very different histories of capital spending will show very different depreciation charges even if their current operations are similar.

By adding all four back, EBITDA aims to approximate the cash-generating power of a company's core operations, independent of its financing structure, tax situation, and accounting choices about past investments. This makes it popular for comparing companies of different sizes, in different countries, or with different capital structures — and it's especially common in industries with large upfront investments, like telecommunications, manufacturing, or private equity, where depreciation charges can be enormous and swing net income around dramatically.

However, EBITDA has well-known limitations, and it's worth treating with some skepticism rather than as a magic number. The most important critique: depreciation and amortization exist because companies really do need to replace equipment, renovate facilities, and maintain infrastructure — these aren't fictional costs. A company with high EBITDA but enormous, unavoidable capital expenditures every year might have very little actual free cash available to its owners. Warren Buffett has famously criticized EBITDA for this reason, asking (paraphrased) whether management thinks the "tooth fairy" pays for capital expenditures.

EBITDA also ignores interest and taxes entirely, even though for most companies these are real cash obligations that must be paid — a highly leveraged company with strong EBITDA can still go bankrupt if it can't cover its interest payments.

The practical takeaway: EBITDA is a useful starting point for comparing the operational scale and profitability of different businesses, and it's a standard building block in valuation (the "EV/EBITDA" ratio is a common alternative to the price-to-earnings ratio). But it should never be the only number you look at. Pair it with net income, free cash flow (cash from operations minus capital expenditures), and the company's debt levels to get a fuller, more honest picture of financial health.`
  },
  {
    id: 'depreciation',
    title: 'Depreciation: Spreading Out the Cost of Big Purchases',
    body: `When a company buys a delivery truck for $40,000, it doesn't typically record a $40,000 expense the moment the truck is purchased — even though $40,000 in cash genuinely left the bank account that day. Instead, accounting rules require the company to spread that cost out over the truck's useful life, recording a portion of it as an expense each year. This process is called depreciation, and it exists to match expenses with the revenue they help generate.

The logic is about timing and fairness in measurement. The truck will help the business deliver products and earn revenue for, say, the next eight years. If the entire $40,000 were expensed in year one, that year's income statement would look artificially terrible (one huge expense, no offsetting benefit yet), while the following seven years would look artificially great (the truck keeps helping generate revenue, but its cost no longer appears as an expense at all). Depreciation fixes this by recognizing, say, $5,000 of expense per year for eight years — roughly matching the cost to the years the truck is actually being used.

The simplest and most common method is straight-line depreciation: take the cost of the asset, subtract its estimated "salvage value" (what it might be worth at the end of its useful life, often assumed to be zero or small), and divide by the number of years of useful life. A $40,000 truck with a $4,000 salvage value and an 8-year useful life would depreciate by ($40,000 − $4,000) ÷ 8 = $4,500 per year.

Other methods exist too. "Accelerated" methods, like double-declining balance, front-load more depreciation into the early years of an asset's life — useful for assets (like computers or vehicles) that genuinely lose value faster early on, and often advantageous for tax purposes because it defers tax payments into the future (a benefit related to the time value of money). Tax law in many countries also allows for special accelerated depreciation rules (such as "bonus depreciation" or "Section 179" in the U.S.) that let businesses deduct a large portion of an asset's cost immediately for tax purposes, even if they use straight-line depreciation on their official financial statements — these are two different sets of books kept for two different purposes, both entirely legitimate.

A related concept is amortization, which is essentially the same idea applied to intangible assets — patents, trademarks, copyrights, or the "goodwill" recorded when one company acquires another. A patent with a 10-year remaining legal life might be amortized at 10% of its value per year.

The most important thing to remember about depreciation is that it's a non-cash expense — it reduces reported profit without any cash actually leaving the business in that period (the cash already left when the asset was originally purchased). This is exactly why the cash flow statement adds depreciation back to net income when calculating cash from operations, and it's why a company can show relatively low net income (due to heavy depreciation) while still generating substantial cash. Understanding depreciation is often the key that unlocks the gap between "the company isn't very profitable on paper" and "the company is actually generating plenty of cash."`
  },
  {
    id: 'budgeting-basics',
    title: 'Budgeting Basics: A Few Frameworks That Actually Work',
    body: `Budgeting has a branding problem — it sounds restrictive, like a diet for your money. But at its core, a budget is just a plan for where your money goes, made in advance, so that your spending reflects your actual priorities rather than just whatever happens to come up. A handful of simple frameworks make this much easier than starting from a blank spreadsheet.

The most well-known is the 50/30/20 rule: roughly 50% of after-tax income goes to needs (housing, groceries, utilities, minimum debt payments, transportation), 30% to wants (dining out, entertainment, hobbies, subscriptions), and 20% to savings and extra debt repayment. It's popular because it's simple enough to use without tracking every transaction — you just need to know your three category totals each month. The exact percentages aren't sacred; in a high cost-of-living area, "needs" might genuinely take up 65-70%, and that's fine as a starting point for understanding where adjustments are possible.

A more rigorous approach is zero-based budgeting, where every dollar of income is assigned a job before the month begins — including a category for savings and even for "miscellaneous" or "fun money" — until income minus all allocations equals zero. This doesn't mean spending everything; it means every dollar, including the dollars going into savings or investments, has a named destination. The benefit is that it forces explicit decisions ("yes, I am choosing to allocate $200 to dining out this month") rather than discovering at month's end where the money went.

A third approach, sometimes called "pay yourself first," flips the usual order of operations. Instead of saving whatever is left over after spending (which, for many people, turns out to be nothing), a fixed amount or percentage is automatically routed to savings or investments the moment income arrives — often via automatic transfers timed to paychecks — and everyday spending happens with whatever remains. This approach leans on a well-documented behavioral finding: money that's "out of sight" in a separate account is much less likely to be spent than money sitting in a checking account, regardless of how disciplined someone intends to be.

Whichever framework you use, a few practices make budgeting far more effective. First, track actual spending for at least one full month before making a plan — most people are surprised by at least one category (subscriptions and food delivery are common culprits). Second, build in a buffer category for irregular expenses — car repairs, medical bills, gifts, annual subscriptions — so they don't feel like emergencies every time they occur; dividing annual or occasional costs by 12 and setting that amount aside monthly turns "surprise" expenses into routine ones. Third, review and adjust monthly rather than trying to build the perfect budget on the first attempt; a budget is a living plan, not a one-time exam.

Finally, it helps to connect budgeting back to the bigger financial picture: a budget governs cash flow (money in vs. money out each month), while net worth (assets minus liabilities) tracks the longer-term result. A good budget is ultimately just the mechanism that, month after month, turns income into a growing net worth — through savings, investments, and debt paid down — rather than letting it simply pass through.`
  }
];
